domain_path: C:\Users\Maria\Desktop\platform_vitis\platform\export\platform\sw\standalone_ps7_cortexa9_0
app_src_dir: F:\Apps\Vivado\Vitis\2024.1\data\embeddedsw\lib\sw_apps\hello_world
template: hello_world
